name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2

      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          # I wasn't able to figure out how to
          # not get a difference in generated output.
          # The action uses a more recent version of
          # tree-sitter-cli
          generate: false
          test-node: ${{runner.os == 'Linux'}}
          test-rust: ${{runner.os == 'Linux'}}

      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/*.lhs